#![allow(unused)]

struct Solution;

impl Solution {
    /// [3474. Lexicographically Smallest Generated String](https://leetcode.com/problems/lexicographically-smallest-generated-string)
    ///
    /// You are given two strings, str1 and str2, of lengths n and m, respectively.
    ///
    /// A string word of length n + m - 1 is defined to be generated by str1 and str2
    /// if it satisfies the following conditions for each index 0 <= i <= n - 1:
    /// - If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
    /// - If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
    ///
    /// Return the lexicographically smallest possible string that can be generated by str1 and str2.
    /// If no string can be generated, return an empty string "".
    ///
    pub fn generate_string(str1: String, str2: String) -> String {
        let mut container = vec!['a'; str1.len() + str2.len() - 1];
        let mut fixed = vec![false; str1.len() + str2.len() - 1];
        let template = str2.chars().collect::<Vec<char>>();

        for (offset, char) in str1.chars().enumerate() {
            match char {
                'T' => {
                    for i in 0..str2.len() {
                        if fixed[offset + i] && container[offset + i] != template[i] {
                            return String::new();
                        } else {
                            container[offset + i] = template[i];
                            fixed[offset + i] = true;
                        }
                    }
                }
                _ => {}
            }
        }
        'outer: for (offset, char) in str1.chars().enumerate() {
            match char {
                'F' => {
                    let mut last_free_i = usize::MAX;
                    for i in (0..template.len()).rev() {
                        if container[offset + i] != template[i] {
                            continue 'outer; //  no strict restrictions
                        }
                        if last_free_i == usize::MAX && !fixed[offset + i] {
                            last_free_i = i;
                        }
                    }
                    if last_free_i != usize::MAX {
                        container[offset + last_free_i] = 'b';
                    } else {
                        return String::new();
                    }
                }
                _ => {}
            }
        }
        // dbg!(container.clone());

        container.into_iter().collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_1() {
        let ret = Solution::generate_string("TFTF".to_owned(), "ab".to_owned());
        assert_eq!(ret, "ababa");
    }

    #[test]
    fn test_2() {
        let ret = Solution::generate_string("TFTF".to_owned(), "abc".to_owned());
        assert_eq!(ret, "");
    }

    #[test]
    fn test_3() {
        let ret = Solution::generate_string("F".to_owned(), "b".to_owned());
        assert_eq!(ret, "a");
    }

    #[test]
    fn test_723() {
        let ret = Solution::generate_string("TTFFT".to_owned(), "fff".to_owned());
        assert_eq!(ret, "");
    }

    #[test]
    fn test_698() {
        let ret = Solution::generate_string("FT".to_owned(), "wvxyy".to_owned());
        assert_eq!(ret, "awvxyy");
    }

    #[test]
    fn test_726() {
        let ret = Solution::generate_string("FFTFFF".to_owned(), "a".to_owned());
        assert_eq!(ret, "bbabbb");
    }

    #[test]
    fn test_726_2() {
        let ret = Solution::generate_string("F".to_owned(), "da".to_owned());
        assert_eq!(ret, "aa");
    }
}
